version: "3.5"

services:
  mysql:
    image: mysql:8.0.28-debian
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
