import { describe, expect, it } from "vitest";
import { scrapeColorCodedLyrics } from "./caption-editor-utils";

describe(scrapeColorCodedLyrics.name, () => {
  it("basic", async () => {
    const res = await scrapeColorCodedLyrics(
      "https://colorcodedlyrics.com/2020/10/26/twice-say-something/"
    );
    expect(res).toMatchInlineSnapshot(`
      [
        [
          "매일이 별다를 것 없던",
          "기억들이 변해가는 것 같아",
          "Where are we 우린 어디쯤인 걸까 가끔은",
          "맘이 기울어",
          "I’ve been waiting for you",
          "(Two of us)",
          "달이 기울면 I’m ready for you",
          "(Both of us)",
          "아무런 예고 없이 다가온",
          "그리 낯설지 않았던",
          "느린 시간 속 심장은 빨라지고",
          "이 도시의 빛이 꺼질 때쯤",
          "아스라이 감은 눈을 뜨면",
          "내 이름이 들려오는 이 순간에",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "늘 혼자 서 있는 가로등은",
          "어느 누구를 기다리고 있을까",
          "똑같은 표정의 불빛들이",
          "오늘은 달라 보여서",
          "맘이 기울어",
          "I’ve been waiting for you",
          "(Two of us)",
          "달이 기울면 I’m ready for you",
          "(Both of us)",
          "변덕스러운 밤이 차가워지고",
          "그만큼 낯설지 않았던",
          "느린 시간 속 심장은 빨라지고",
          "이 도시의 빛이 꺼질 때쯤",
          "아스라이 감은 눈을 뜨면",
          "내 이름이 들려오는 이 순간에",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "도시의 사각 틈 사이로",
          "새어 나온 불빛 나를 감싸면",
          "맘을 말해 줘",
          "느린 시간 속 심장은 빨라지고 (빨라지고)",
          "이 도시의 빛이 꺼질 때쯤 (빛이 꺼질 때쯤)",
          "아스라이 감은 눈을 뜨면",
          "[",
          "사",
          "/",
          "지",
          "] 내 이름이 들려오는 이 순간에",
          "Say something",
          "(Say something)",
          "Say something",
          "(Oh)",
          "Say something",
          "(Nanananananana)",
          "Say something",
          "Say something",
          "(Oh)",
          "Say something",
          "Say something",
          "(Say something)",
          "Say something",
        ],
        [
          "The memories that were the same every day…",
          "…seem to be changing",
          "Where are we, around where are we at, sometimes",
          "My heart tilts",
          "I’ve been waiting for you (Two of us)",
          "When the moon wanes, I’m ready for you (Both of us)",
          "Approached without any warnings",
          "But wasn’t too unfamiliar",
          "In this slow time, my heart speeds up",
          "And when the city lights are about to turn off",
          "When I open my gently closed eyes",
          "At this moment when my name is called",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "The streetlamp always standing alone",
          "Who is it waiting for?",
          "The lights with the same expression…",
          "…seem different today",
          "My heart tilts",
          "I’ve been waiting for you (Two of us)",
          "When the moon wanes, I’m ready for you (Both of us)",
          "The whimsical night gets cold",
          "And it wasn’t so unfamiliar",
          "In this slow time, my heart speeds up",
          "And when the city lights are about to turn off",
          "When I open my gently closed eyes",
          "At this moment when my name is called",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Between the squares of this city’s dawn",
          "When the light that slipped past the gap envelops me",
          "Tell me how you feel",
          "In this slow time, my heart speeds up",
          "And when the city lights are about to turn off",
          "When I open my gently closed eyes",
          "At this moment when my name is called",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
          "Say something",
        ],
      ]
    `);
  });
});
