import { randomBytes } from "node:crypto";
import { promisify } from "node:util";
import * as argon2 from "@hiogawa/argon2-wasm-bindgen/dist/index-wasm-bundle";
import { once } from "@hiogawa/utils";

// argon2 password hashing
// https://github.com/bitwarden/clients/pull/4468
// https://github.com/bitwarden/server/pull/2583
// https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id
// https://github.com/RustCrypto/password-hashes/blob/dc23aa160f010bcb02050ae230be868d84367c1d/argon2/README.md
// https://github.com/hi-ogawa/argon2-wasm-bindgen

const initializeArgon2WasmOnce = once(async () => {
  await argon2.initializeBundle();
});

const randomBytesPromise = promisify(randomBytes);

async function generateSalt(): Promise<string> {
  const saltLength = 16;
  const saltBuffer = await randomBytesPromise(saltLength);
  return saltBuffer.toString("base64").replaceAll("=", "");
}

export async function toPasswordHash(password: string): Promise<string> {
  await initializeArgon2WasmOnce();

  const salt = await generateSalt();
  return argon2.hash_password(password, salt);
}

export async function verifyPassword(
  password: string,
  passwordHash: string
): Promise<boolean> {
  await initializeArgon2WasmOnce();

  return argon2.verify_password(password, passwordHash);
}

// fake verification for timing safety?
export async function verifyPasswordNoop() {
  await verifyPassword(
    "noop-for-timing-safety",
    // dummy hash generated by
    //   node -r esbuild-register -e 'require("./app/utils/password-utils.ts").toPasswordHash("").then(console.log)'
    "$argon2id$v=19$m=19456,t=2,p=1$9i2rshv5CH6kecJSbN0pLw$sCqIUzQzO2gC+TewudcBIcGX9kPtxIaXCaIbEiX7ecI"
  );
}
