import { randomBytes } from "node:crypto";
import { promisify } from "node:util";
import { initComlinkProxy } from "@hiogawa/argon2-wasm-bindgen/dist/comlink-node-proxy";

// argon2 password hashing
// https://github.com/bitwarden/clients/pull/4468
// https://github.com/bitwarden/server/pull/2583
// https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id
// https://github.com/RustCrypto/password-hashes/blob/dc23aa160f010bcb02050ae230be868d84367c1d/argon2/README.md
// https://github.com/hi-ogawa/argon2-wasm-bindgen

let proxy: Awaited<ReturnType<typeof initComlinkProxy>>;

export async function initializeArgon2() {
  proxy = await initComlinkProxy();
  await proxy.argon2.initBundle();
}

export async function finalizeArgon2() {
  if (proxy) {
    await proxy.worker.terminate();
  }
}

const randomBytesPromise = promisify(randomBytes);

async function generateSalt(): Promise<string> {
  const saltLength = 16;
  const saltBuffer = await randomBytesPromise(saltLength);
  return saltBuffer.toString("base64").replaceAll("=", "");
}

export async function toPasswordHash(password: string): Promise<string> {
  const salt = await generateSalt();
  return proxy.argon2.hash_password(password, salt);
}

export async function verifyPassword(
  password: string,
  passwordHash: string
): Promise<boolean> {
  // check old bcrypt hash and show specific message
  if (passwordHash.startsWith("$2a$")) {
    throw new Error(
      "Your password has been reset. Please create a new password from 'Forget your password'."
    );
  }

  return proxy.argon2.verify_password(password, passwordHash);
}

// fake verification for timing safety?
export async function verifyPasswordNoop() {
  await verifyPassword(
    "noop-for-timing-safety",
    // dummy hash generated by
    //   node -r esbuild-register -e 'lib = require("./app/utils/password-utils.ts"); lib.initializeArgon2().then(() => lib.toPasswordHash("").then(console.log))'
    "$argon2id$v=19$m=19456,t=2,p=1$9i2rshv5CH6kecJSbN0pLw$sCqIUzQzO2gC+TewudcBIcGX9kPtxIaXCaIbEiX7ecI"
  );
}
