import { randomBytes } from "node:crypto";
import { promisify } from "node:util";
import { Worker } from "node:worker_threads";
import type { Argon2 } from "@hiogawa/argon2-wasm-bindgen/dist/comlink-node";
import { once } from "@hiogawa/utils";
import { type Remote, wrap } from "comlink";
import comlinkNodeAdapter from "comlink/dist/umd/node-adapter";

// argon2 password hashing
// https://github.com/bitwarden/clients/pull/4468
// https://github.com/bitwarden/server/pull/2583
// https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id
// https://github.com/RustCrypto/password-hashes/blob/dc23aa160f010bcb02050ae230be868d84367c1d/argon2/README.md
// https://github.com/hi-ogawa/argon2-wasm-bindgen

let worker: Worker;
let argon2: Remote<Argon2>;

const initializeArgon2 = once(async () => {
  // use prebuilt comlink worker code
  worker = new Worker(
    "./node_modules/@hiogawa/argon2-wasm-bindgen/dist/comlink-node.cjs"
  );
  argon2 = wrap(comlinkNodeAdapter(worker));
  await argon2.initBundle();
});

export async function finalizeArgon2() {
  if (worker) {
    await worker.terminate();
  }
}

const randomBytesPromise = promisify(randomBytes);

async function generateSalt(): Promise<string> {
  const saltLength = 16;
  const saltBuffer = await randomBytesPromise(saltLength);
  return saltBuffer.toString("base64").replaceAll("=", "");
}

export async function toPasswordHash(password: string): Promise<string> {
  await initializeArgon2();

  const salt = await generateSalt();
  return argon2.hash_password(password, salt);
}

export async function verifyPassword(
  password: string,
  passwordHash: string
): Promise<boolean> {
  await initializeArgon2();

  // check old bcrypt hash and show specific message
  if (passwordHash.startsWith("$2a$")) {
    throw new Error(
      "Your password has been reset. Please create a new password from 'Forget your password'."
    );
  }

  return argon2.verify_password(password, passwordHash);
}

// fake verification for timing safety?
export async function verifyPasswordNoop() {
  await verifyPassword(
    "noop-for-timing-safety",
    // dummy hash generated by
    //   node -r esbuild-register -e 'require("./app/utils/password-utils.ts").toPasswordHash("").then(console.log)'
    "$argon2id$v=19$m=19456,t=2,p=1$9i2rshv5CH6kecJSbN0pLw$sCqIUzQzO2gC+TewudcBIcGX9kPtxIaXCaIbEiX7ecI"
  );
}
