name: ci
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: make lint
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm i
      - run: make docker/up db/reset/test db/seed-download
      - run: pnpm test-coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-unit
          path: coverage

  test-e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm i
      - uses: actions/cache@v3
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: cache-playwright-1.31.2
      - if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - run: make docker/up db/reset/test db/seed-download
      - run: E2E_CLIENT_TRACE=1 pnpm test-e2e-coverage
      - run: rm -rf coverage/e2e-client/tmp coverage/e2e-server/tmp
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-e2e-server
          path: coverage/e2e-server
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-e2e
          path: test-results

  test-migrations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm i
      - run: make docker/up db/recreate
      - run: pnpm cli db:test-migrations --unit-test
      - run: pnpm cli db:test-migrations --reversibility-test

  publish-coverage-report:
    runs-on: ubuntu-20.04
    needs:
      - test
      - test-e2e
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm i
      - uses: actions/download-artifact@v3
        with:
          name: coverage-unit
          path: coverage/unit
      - uses: actions/download-artifact@v3
        with:
          name: coverage-e2e-server
          path: coverage/e2e-server
      - name: publish report
        run: |
          echo "== HTML PREVIEW URL =="
          echo "https://htmlpreview.github.io/?https://raw.githubusercontent.com/hi-ogawa/ytsub-v3/__coverage__/unit/index.html"
          echo "https://htmlpreview.github.io/?https://raw.githubusercontent.com/hi-ogawa/ytsub-v3/__coverage__/e2e-server/index.html"
          echo "======================"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NODE_DEBUG=gh-pages npx gh-pages --branch __coverage__ --dist coverage --repo "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
