name: CI
"on":
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npm run lint

  tsc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npm run tsc

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npm run netlify:build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: make docker/up db/reset/test
      - run: npm run test

  test-e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: make docker/up db/reset/test
      - run: npm run test:e2e

  test-migrations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: make docker/up db/recreate
      - run: npm run cli -- db:test-migrations

  lint-misc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make lint/all
