name: ci
"on":
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npm run lint:check

  tsc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npm run tsc

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npm run netlify:build

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: make docker/up db/reset/test
      - run: npm run test:coverage
      - name: publish coverage
        run: |
          echo "== HTML PREVIEW URL =="
          echo "https://htmlpreview.github.io/?https://raw.githubusercontent.com/hi-ogawa/ytsub-v3/__coverage__/$(git rev-parse HEAD)/index.html"
          echo "======================"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm run test:coverage:publish -- --repo "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

  test-e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: make docker/up db/reset/test
      - run: npm run test-e2e

  test-migrations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: pnpm run install-with-patch -- --frozen-lockfile
      - run: make docker/up db/recreate
      - run: npm run cli -- db:test-migrations --unit-test
      - run: npm run cli -- db:test-migrations --reversibility-test

  lint-misc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make lint/all
