name: deps-update
"on":
  push:
  # manually by workflow dispatch or cron job
  workflow_dispatch:
  # schedule:
  #   # every week (cf. https://crontab.guru/#0_0_*_*_0)
  #   cron: "0 0 * * 0"
jobs:
  deps-update-pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i
      - run: pnpm update
      # https://stackoverflow.com/a/73340290
      - name: create PR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          base_name="$GITHUB_REF_NAME"
          branch_name="__depsUpdate__$GITHUB_REF_NAME"
          git checkout -b "$branch_name"
          git add .
          git commit -m deps-update
          git push -f origin "$branch_name"
          gh pr create --base "$base_name" --head "$branch_name" --title deps-update --body deps-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
