name: health-check
"on":
  schedule:
    # every hour
    - cron: "0 * * * *"
jobs:
  health-check:
    runs-on: ubuntu-20.04
    container:
      image: badouralix/curl-jq
    steps:
      - run: curl https://ytsub-v3-hiro18181.vercel.app/health-check | jq --exit-status '.success'

  # TODO: wake up planetscale by database write
  health-check-db:
    runs-on: ubuntu-20.04
    container:
      image: badouralix/curl-jq
    steps:
      - run: curl https://ytsub-v3-hiro18181.vercel.app/health-check-db | jq --exit-status '.success'
