#
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
# >  The shortest interval you can run scheduled workflows is once every 5 minutes.
#
name: health-check
"on":
  # run health check at every 10th minute to warm up aws lambda
  #   60 / 10 * 24 * 30 = 4,320
  schedule:
    - cron: "*/10 * * * *"
jobs:
  health-check:
    runs-on: ubuntu-20.04
    container:
      image: badouralix/curl-jq
    steps:
      - run: curl https://ytsub-v3-hiro18181.vercel.app/health-check | jq --exit-status '.success'
