name: health-check
"on":
  schedule:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    # >  The shortest interval you can run scheduled workflows is once every 5 minutes.
    - cron: "*/30 * * * *"
jobs:
  health-check:
    runs-on: ubuntu-20.04
    container:
      image: badouralix/curl-jq
    steps:
      - run: curl https://ytsub-v3-hiro18181.vercel.app/health-check | jq --exit-status '.success'

  # TODO: wake up planetscale by triggering misc databaase write
  # wake-db:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: echo todo
