name: health-check
"on":
  workflow_dispatch:
  schedule:
    # every hour
    - cron: "0 * * * *"
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSfL https://ytsub-v3-hiro18181.vercel.app/dev/health-check-db | jq --exit-status
